[package]
name = "playground_rust"
version = "0.1.0-irreleventSemanticVersioning.69420" 
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# random
text_io = "0.1.10"
rand = "0.8.5"
