#define DLL_EXTRA_PATH "c:\\users\\radsammyt\\appdata\\local\\programs\\python\\python310"
#define NO_PYTHON_WARNINGS 0
#define NUITKA_MAIN_MODULE_NAME "__main__"
#define PYTHON_HOME_PATH "C:\\Users\\RadsammyT\\AppData\\Local\\Programs\\Python\\Python310"
#define SYSFLAG_BYTES_WARNING 0
#define SYSFLAG_NO_RANDOMIZATION 0
#define SYSFLAG_NO_SITE 0
#define SYSFLAG_OPTIMIZE 0
#define SYSFLAG_UNBUFFERED 0
#define SYSFLAG_UTF8 0
#define SYSFLAG_VERBOSE 0
